### ISSUE TITLE
OpenCL hangs with ROCm 6.0.*

### ISSUE THREAD

**Issue by oleid** [sjnewbury/rocm-bleeding-edge#3]
Hi,

thanks for maintaining this repository. I was trying out ROCm today with a RX 7900 XTX, however, everything I tried seems to hang after building the OpenCL kernel. By hang I mean the application seems to be waiting for the kernel to finish. The system itself doesn't hang.

* `app-crypt/johntheripper-jumbo` with USE += opencl and calling `john --test --format=wpapsk-opencl  --device=1`
* luxmark
* indigo benchmark https://www.indigorenderer.com/indigobench

Yet, when using rocm-6.1.1 from a debian stable chroot with upstream rocm packages, things appear to work.
I.e. I run `LD_LIBRARY_PATH=/mnt/debian/opt/rocm-6.1.1/lib/ ./indigo_benchmark` and the rendering is just fine.

So I wondering if using 6.1.1 on gentoo would solve the issue or if there is an issue while building the packages.
Are there plans to upgrade to ROCm 6.1.1?

**Comment by sjnewbury** [comment]
I haven't tested it on anything newer than Vega, but it *should* work.   Do you have any messages in your kernel log?

**Comment by oleid** [comment]
I cannot reproduce it it anymore.
Apparently some upgrade in the last few months solved the issue.
